import os
from dotenv import load_dotenv

load_dotenv()

SLACK_BOT_TOKEN = os.getenv("SLACK_BOT_TOKEN")
SLACK_ISSUE_CHANNEL= os.getenv("SLACK_ISSUE_CHANNEL")
SLACK_INCIDENTS_CHANNEL= os.getenv("SLACK_INCIDENTS_CHANNEL")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_WEBHOOK_SECRET = os.getenv("GITHUB_WEBHOOK_SECRET")
